### ISSUE TITLE
Add possibility to expose multiple identities under the same domain name

### ISSUE THREAD

**Issue by jloic** [w3c-ccg/did-method-web#2]
Since virtually every other did-resolver is able to expose multiple identities, I'd like to use a single domain to expose multiple DID. Accepting a path after the domain name would go a long way, but if it clashes then we can split the path with something different.
Example:
 "did:web:my.domain.com|{uuid}" that would resolve to 
 - https://my.domain.com/did/{uuid}

**Comment by gribneau** [comment]
I've suggested adding a parameter to the well-known URL rather than changing it.
https://github.com/w3c-ccg/did-method-web/pull/4

**Comment by dmitrizagidulin** [comment]
I think the DID:web method should support _both_:
* Discovery of a DID document given a bare domain name (with no path) (through either the `.well-known/` or the DNS TXT mechanisms).
* Ability for any arbitrary path to house a DID document. I want to be able to use `did:web:example.com/dmitri/did.json` as my DID.

**Comment by gribneau** [comment]
I agree, particularly with the arbitrary path case above.

I would be happy to contribute a definition for that, if you like. (I've actually been working on it separately.)

**Comment by dmitrizagidulin** [comment]
@gribneau Go for it, that would be great! :)

**Comment by dmitrizagidulin** [comment]
(The discussion continues on PR #5.)

**Comment by OR13** [comment]
Demo: https://did-web.web.app/ (uses 302 redirect for both variants).

**Comment by dmitrizagidulin** [comment]
Implemented in PR #5, closing.
