### ISSUE TITLE
"publicKey" not defined in did-core

### ISSUE THREAD

**Issue by letmaik** [w3c-ccg/did-method-web#27]
Example 1 uses `"publicKey"` which is not defined in https://www.w3.org/TR/did-core/

Am I missing something?

**Comment by dmitrizagidulin** [comment]
Hi @letmaik -- no, you're absolutely right, we just need to update the did:web spec.
(`publicKey` got renamed to `verificationMethod`, in the DID Core spec.)

**Comment by dmitrizagidulin** [comment]
@letmaik - This should be addressed by PR https://github.com/w3c-ccg/did-method-web/pull/28
