### ISSUE TITLE
Should it be possible to indicate a port with did:web?

### ISSUE THREAD

**Issue by kdenhartog** [w3c-ccg/did-method-web#34]
Typically in a web domain a port is a part of the host authority and indicated via a `:` followed by a number. However due to the way we're currently parsing a resource path we're using the `:` which maps to a `/` and changes the resource path. This leaves no way for a port to be specified with the did:web URI. Is this an expected feature or something that's just been overlooked.

@OR13 @dmitrizagidulin @dlongley @rhiaro I'd think you all may have an opinion on this.

**Comment by mirceanis** [comment]
I think this was already handled in #7.
The conclusion was that you should use `encodeUriComponent(host:port)` as well as for each path component.

**Comment by kdenhartog** [comment]
Thanks for linking to that. Will close this one.
