### ISSUE TITLE
replace owner with controller?

### ISSUE THREAD

**Issue by ghost** [w3c-ccg/did-method-web#56]
https://github.com/w3c-ccg/did-method-web/blob/53ac2038367408ff9430ba05553a1132fff5ad9c/index.html#L142
https://github.com/w3c-ccg/did-method-web/blob/53ac2038367408ff9430ba05553a1132fff5ad9c/index.html#L144
https://github.com/w3c-ccg/did-method-web/blob/53ac2038367408ff9430ba05553a1132fff5ad9c/index.html#L148

**Comment by clehner** [comment]
This was done in #57.
