### ISSUE TITLE
by creating DID in this method we can verify from third party ??

### ISSUE THREAD

**Issue by Muthurajj** [w3c-ccg/did-method-web#65]
by creating the DID in WEB method the verifiable credential can be verified from the third party verifiers??
creating DID in web method will visible to verifier to access the VC??

**Comment by jceb** [comment]
Yes, that is possible. The third party would resolve the did:web DID by requesting the DID document from your web server and then proceed to verify the VC.

**Comment by Muthurajj** [comment]
thank for the reply, I have some points to clear correct me if wrong
1.I have create http:// <some domain name>.io URL like this then import the DID document in that URL 
2. then create a DID like did:web:<domainname.io>: file name

**Comment by jceb** [comment]
Yes, almost.

a) ensure that your webserver is reachable via HTTPS with a valid certificate, e.g. at https://domainname.io
b) the filename that you need to create is `did.json` including any leading directories, e.g. for DID `did:web:domainname.io:myid` you HTTPS server would need to serve the DID document at `https://domainname.io/myid/did.json`. You'll find more examples in the spec.

**Comment by Muthurajj** [comment]
thank, you to have any idea about the did document structure for did:web method

**Comment by jceb** [comment]
Take a look at the [DID Core Spec](https://w3c.github.io/did-core/)

**Comment by Muthurajj** [comment]
1.In did document we have mentioned the service endpoint , The service endpoint is reference to issuer url ?
2.while verifying the vc the verifier will access the endpoint url to check the credentials ??

**Comment by Muthurajj** [comment]
> Take a look at the [DID Core Spec](https://w3c.github.io/did-core/)

thanks its very useful.

**Comment by jceb** [comment]
> 1.In did document we have mentioned the service endpoint , The service endpoint is reference to issuer url ?

It doesn't have to be the issuer URL it could be any URL.

> 2.while verifying the vc the verifier will access the endpoint url to check the credentials ??

No, the verification is actually designed to not required a back-channel. For the simple verification of the credential it's enough to have access to the credential and the DID documents of the issuer and the holder/presenter. These documents are cryptographically inter-linked to verify that the issuer made a statement (credential) about the holder. See the VC spec for more details.

**Comment by Muthurajj** [comment]
can i upload my did document in google drive and can i share the url in VC??

**Comment by Muthurajj** [comment]
The did:web method required any blockchain storage for storing the did??

**Comment by jceb** [comment]
No, it doesn't.

**Comment by Muthurajj** [comment]
Thanks for the support @jceb
